imports:
    - { resource: 'services.yaml' }

services:
    Ssch\TYPO3Rector\Rector\Core\DataHandling\DataHandlerRmCommaRector: ~
    Ssch\TYPO3Rector\Rector\Core\TypoScript\TemplateServiceSplitConfArrayRector:
    Ssch\TYPO3Rector\Rector\Frontend\ContentObject\RefactorRemovedMarkerMethodsFromContentObjectRendererRector: ~
    Ssch\TYPO3Rector\Rector\Extbase\ChangeAttemptsParameterConsoleOutputRector:
    Rector\Renaming\Rector\Class_\RenameClassRector:
        $oldToNewClasses:
            TYPO3\CMS\Extbase\Service\TypoScriptService: TYPO3\CMS\Core\TypoScript\TypoScriptService
