services:
  Ssch\TYPO3Rector\Core\Page\RefactorDeprecatedConcatenateMethodsPageRendererRector: ~
  Ssch\TYPO3Rector\Frontend\ContentObject\CallEnableFieldsFromPageRepositoryRector: ~
  Rector\Renaming\Rector\Class_\RenameClassRector:
    $oldToNewClasses:
        TYPO3\CMS\Saltedpasswords\Salt\Argon2iSalt: TYPO3\CMS\Core\Crypto\PasswordHashing\Argon2iPasswordHash
        TYPO3\CMS\Saltedpasswords\Salt\BcryptSalt: TYPO3\CMS\Core\Crypto\PasswordHashing\BcryptPasswordHash
        TYPO3\CMS\Saltedpasswords\Salt\BlowfishSalt: TYPO3\CMS\Core\Crypto\PasswordHashing\BlowfishPasswordHash
        TYPO3\CMS\Saltedpasswords\Exception\InvalidSaltException: TYPO3\CMS\Core\Crypto\PasswordHashing\InvalidPasswordHashException
        TYPO3\CMS\Saltedpasswords\Salt\Md5Salt: TYPO3\CMS\Core\Crypto\PasswordHashing\Md5PasswordHash
        TYPO3\CMS\Saltedpasswords\Salt\SaltFactory: TYPO3\CMS\Core\Crypto\PasswordHashing\PasswordHashFactory
        TYPO3\CMS\Saltedpasswords\Salt\SaltInterface: TYPO3\CMS\Core\Crypto\PasswordHashing\PasswordHashInterface
        TYPO3\CMS\Saltedpasswords\Salt\Pbkdf2Salt: TYPO3\CMS\Core\Crypto\PasswordHashing\Pbkdf2PasswordHash
        TYPO3\CMS\Saltedpasswords\Salt\PhpassSalt: TYPO3\CMS\Core\Crypto\PasswordHashing\PhpassPasswordHash
        TYPO3\CMS\Saltedpasswords\Salt\AbstractComposedSalt: TYPO3\CMS\Core\Crypto\PasswordHashing\AbstractComposedSalt
        TYPO3\CMS\Saltedpasswords\Salt\ComposedSaltInterface: TYPO3\CMS\Core\Crypto\PasswordHashing\ComposedPasswordHashInterface
        TYPO3\CMS\Saltedpasswords\Utility\ExensionManagerConfigurationUtility: TYPO3\CMS\Core\Crypto\PasswordHashing\ExtensionManagerConfigurationUtility
        TYPO3\CMS\Saltedpasswords\SaltedPasswordService: TYPO3\CMS\Core\Crypto\PasswordHashing\SaltedPasswordService
        TYPO3\CMS\Saltedpasswords\Utility\SaltedPasswordsUtility: TYPO3\CMS\Core\Crypto\PasswordHashing\SaltedPasswordsUtility
